    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.0.0
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Printrbot Play HB Printrboard RevF Development Build"
        files: |
          firmware.hex
        id: "automatic_releases"