name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Build Marlin
      run: |
        pip install platformio
        ./buildroot/bin/generate_version
        platformio run
        cd .pio/build/at90usb1286_dfu/
        mkdir artifacts
        mv firmware.hex artifacts/
    - name: Upload firmware
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Printrbot-Play-HB-Printrboard_revF-Marlin_2.0.5.3-firmware
        # Directory containing files to upload
        path: .pio/build/at90usb1286_dfu/artifacts

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.0.0
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Printrbot Play HB Printrboard RevF Development Build"
        files: .pio/build/at90usb1286_dfu/artifacts
        id: "automatic_releases"