name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Build Marlin
      run: |
        pip install platformio
        ./buildroot/bin/generate_version
        platformio run
        cd .pio/build/STM32F103RC_btt_512K/
        mkdir artifacts
        cp firmware.bin artifacts/
    - name: Upload firmware
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: firmware
        # Directory containing files to upload
        path: .pio/build/STM32F103RC_btt_512K/artifacts
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.0.0
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Simple-Metal-SKR-Mini-e3"
        prerelease: false
        title: "Printrbot Simple Metal SKR Mini E3 v1.2"
        files: .pio/build/at90usb1286_dfu/artifacts/firmware.hex

