name: Check & Release
on: [push, pull_request]
jobs:
  build: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Build Marlin
      run: |
        pip install platformio
        ./buildroot/bin/generate_version
        platformio run
        cd .pio/build/at90usb1286_dfu/
        mkdir artifacts
        cp firmware.hex artifacts/
    - name: Upload firmware
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Printrbot-Play-HB-Printrboard_revF-Marlin_2.0.5.3-firmware
        # Directory containing files to upload
        path: .pio/build/at90usb1286_dfu/artifacts
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
        - .pio/build/at90usb1286_dfu/artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}